themefisher/airspace-hugo

layouts/partials/header.html
Hello!  First of all, thank you so much for contributing this beautiful theme to the Hugo community!
The alt text being used for the logo img is currently wrong except for the front page.
instead of saying `alt="Airspace for Hugo Logo"`, it would say `alt="Work Logo"`, `alt="Contact Logo"`, etc. depending on which page the user lands on.
Changing the page-based `.Title` to sitewide `.Site.Title` fixes this issue.
Many thanks!
=> Use .Site.Title (not page .Title) for logo img alt

exampleSite/config.toml, exampleSite/content/service.md
The example site doesn't have a functional `service` link. Changed the link in the config and added `service.md`
=> added service section to example site

README.md
"Common" should be "Commons".  Sorry, I didn't catch that.
The same typo is on https://themefisher.com/license/ too, so please fix it when you have time.
Also, on https://themefisher.com/license/, you might want to add a link to https://creativecommons.org/licenses/by/3.0/, https://creativecommons.org/licenses/by/3.0/legalcode, and/or https://spdx.org/licenses/CC-BY-3.0.html so users can read the full text of the license.
Also, just to make sure, you are using "Creative Commons Attribution 3.0 **Unported**" (and not US or other country-specific version), right?
=> Fix typo and add SPDX short identifier in README.md

exampleSite/config.toml, layouts/_default/list.html, layouts/_default/single.html
Fixes https://github.com/themefisher/airspace-hugo/issues/18. I only changed the name of variable from `date_format` to `dateFormat`.
=> Fix date format error

README.md, theme.toml
This is to ensure https://themes.gohugo.io/airspace-hugo lists the license correctly.
As of this righting, it is still showing MIT as the license.
Also fix the punctuations in the License section in README.md.
Thanks!
=> Reflect license change in theme.toml

layouts/partials/work.html
Currently if you have multiple elements in the portfolio that are from the same category that category will be added multiple times to the selector. That means that having 4 elements of portfolio, 3 of them having category A, and the forth one having category B the selector will be [Everything, A, A, A, B]. If you click in any of the A selectors will bring ALL elements having category A.
My change will allow only unique categories in the selector, so in the previous example the selector will be [Everything, A, B] and it will behave exactly the same as before.
=> Collapse equally named categories in work

README.md
Looks like a recycled README from other page maybe?  Updating to reflect cloning from airspace-hugo repo.
=> fix installation instruction url in README

static/css/style.css
Some browsers won't allow to load mixed content if it is not via an encrypted channel (see https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)
=> use https instead of http for mixed content

exampleSite/config.toml, layouts/_default/list.html, layouts/_default/single.html, layouts/author/single.html
Hi,
Here's a proposal for multi-author support as explained in #71. 
This PR introduces a new site variable named `multi_author`.  
The default value for `multi-author` is `false`: it has been chosen to not introduce any breaking change in the theme.  
When `multi_author` is set to `true`, the `author` parameter in any content MUST be a list.
---
close #71
=> Multi-author support

layouts/partials/footer.html
The footer links always linked to `defaultContentLanguage` pages or – if `defaultContentLanguageInSubdir` was set to `true` in `config.toml` – they were even broken.
=> Fix footer links for multilingual mode

layouts/partials/header.html
Replaces `site.BaseURL` with `"/"`. Using relative URLs is generally more portable, for example it allows deploys to other domains than the `BaseURL`, e.g. with [Netlify's branch deploys](https://docs.netlify.com/site-deploys/overview/#branches-and-deploys).
=> Use relative home URL

exampleSite/config.toml, exampleSite/content/english/blog/blog-post-2.md, layouts/_default/list.html, layouts/_default/single.html, layouts/author/single.html
With this PR, the config option `multi_author` is not needed anymore since both atomic strings as well as string arrays are supported "side-by-side" in the `author` frontmatter param.
=> Simplify multi-author support

netlify.toml
Adds a Netlify redirect rule for the language-specific Italian 404 page (complements https://github.com/themefisher/airspace-hugo/pull/124).
=> Add IT 404 redirect rule for Netlify

layouts/_default/baseof.html, layouts/partials/footer.html
and avert use of [`partialCached`](https://gohugo.io/functions/partialcached/) for `footer.html` since it breaks the conditional logic in there (because with `partialCached` the partial is only executed _once_ per site).
=> Fix Google Maps JS snippet inclusion

layouts/_default/list.html, layouts/_default/service.html, layouts/author/single.html, layouts/index.html, layouts/partials/cta.html, layouts/partials/footer.html, layouts/partials/head.html, layouts/partials/header.html, layouts/partials/page-title.html, layouts/partials/preloader.html, layouts/partials/widgets/recent_posts.html, layouts/project/list.html
Replace `absURL` -> `relURL` and `.Permalink` -> `.RelPermalink` in all remaining places to make the theme more portable, cf. #118
=> Avoid absolute URLs

layouts/partials/cloak_email.html, layouts/partials/date_i18n.html, layouts/shortcodes/cloak_email.html, layouts/shortcodes/date_i18n.html
This ensures that shortcodes and corresponding partials are agnostic to the newline character terminating a file, i.e. allows the files to be [POSIX-compliant](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).
=> Refactor shortcodes and partials to ignore terminating newline

assets/scss/templates/_backgrounds.scss
This centers background images of class `bg-1` horizontally and vertically, which makes them less sensitive to viewport width (better responsive design) and probably is what most users expect.
=> Center `.bg-1` background images

layouts/index.html, layouts/partials/cta.html, layouts/partials/service.html
Opening in a new tab feels weird since the button most likely links to a subpage of the same site.
Additionally, some template files under `layouts/` have been improved to be more robust/flexible when individual fields in corresponding `content/` files are missing or blank.
=> Open banner button link in same tab and make templates more robust/flexible

assets/js/counter.min.js, exampleSite/config.toml, layouts/partials/head.html
[counter.dev](https://counter.dev/) offers a [privacy-friendly](https://counter.dev/privacy.html) and leightweight alternative to Google Analytics that probably satisfies most basic needs. AFAIC it doesn't need any kind of privacy notice / cookie banner in EU jurisdiction (GDPR) since it doesn't collect any personal data from website visitors and doesn't rely on cookies at all. counter.dev is free to use, open source and lives from donations.
=> Add support for counter.dev analytics

layouts/partials/head.html
- Don't use Hugo's [internal Twitter Card template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html) since the `twitter:card` tag is basically hardcoded there.
- Instead introduce our own tag generation logic that is based on the actual image dimensions (if not SVG) and respects the minimum dimensions for Twitters [Summary Card](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary) and [Summary Card with Large Image](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image). If the image is square or its dimensions are below 300x157 (but >= 144x144), a _Summary Card_ will be generated, otherwise a _Summary Card with Large Image_ (or nothing in case image is of type …
=> Tweak Open Graph and Twitter Card metadata generation

i18n/fr.toml
Because of some recent [language/i18n fixes](https://github.com/gohugoio/hugo/releases/tag/v0.83.0), Hugo 0.83+ started to complain about missing `fr` translations for cardinal form `"one"`. This is due to the fact that French uses different language plural rules than English, German, Italian and others. See https://github.com/gohugoio/hugo/issues/7839#issuecomment-830643723 for an explanation of the underlying issue.
=> Fix i18n warning messages with Hugo 0.83+

layouts/_default/about.html, layouts/_default/faq.html, layouts/_default/list.html, layouts/_default/pricing.html, layouts/_default/service.html, layouts/_default/single.html, layouts/author/single.html, layouts/index.html, layouts/partials/date_i18n.html, layouts/partials/widgets/recent_posts.html, layouts/project/list.html, layouts/project/single.html, layouts/shortcodes/date_i18n.html
- Use [`.Page.RenderString (dict "display" 
"block")`](https://gohugo.io/functions/renderstring/) instead of 
`markdownify` for user-defined texts that possibly include multiple 
paragraphs. See https://github.com/gohugoio/hugo/issues/5975 for the 
underlying issue.
- Make the `date_i18n.html` partial work with any date (not tied to 
`PublishDate` anymore) and pretty-format `date_i18n.html` shortcode.
- Localize last modification date on FAQ page.
- Improve templates to be more robust/flexible, i.a. when individual 
fields in corresponding `content/` files are missing or blank.
=> Improve templates

i18n/de.toml, i18n/en.toml, i18n/fr.toml, i18n/it.toml
Hugo [v0.83.1](https://github.com/gohugoio/hugo/releases/tag/v0.83.1) reverted things changed in v0.83, so #147 is a non-solution now.
I've changed i18n files to use the [simple/old translation formalism](https://github.com/gohugoio/hugo/pull/8497#issuecomment-830820941) which [hopefully stays the recommended way to define translations without pluralization rules in Hugo](https://github.com/gohugoio/hugo/pull/8497#issuecomment-831169636)
=> Fix i18n warnings (again) in Hugo v0.83.1:

layouts/_default/list.html, layouts/_default/single.html, layouts/author/single.html, layouts/partials/header.html
As I've learned yesterday, [`.Scratch`](https://gohugo.io/functions/scratch) isn't necessary anymore in most cases since the original scoping issue of template vars has been fixed in Go 1.11 (or Hugo 0.48 respectively). For more info, see [this blog post](https://regisphilibert.com/blog/2017/04/hugo-scratch-explained-variable/).
Avoiding `.Scratch` leads to simpler code that's easier to understand, especially for newcomers.
Additionally, this PR brings some cosmetic changes.
=> Avoid usage of `.Scratch`

layouts/_default/about.html, layouts/_default/list.html, layouts/_default/single.html, layouts/author/single.html, layouts/index.html, layouts/partials/cta.html, layouts/partials/page-title.html, layouts/partials/service.html, layouts/project/list.html, layouts/project/single.html
- Add space after `{{` and before `}}`
- Always lowercase `.Params` names, cf. https://github.com/themefisher/airspace-hugo/pull/116
=> Harmonize go template syntax

layouts/_default/service.html
When key `about.content` in the content file `service.md` is set to a multi-line string, the template generated invalid HTML (which some browsers automatically correct when rendering the page).
This PR fixes the template to *always* generate valid HTML regardless of `about.content`'s line count.
=> Fix HTML in about section on service page

layouts/partials/widgets/taxonomy_category.html
Local variable `$name` is not needed.
=> Simplify template code

exampleSite/config.toml, exampleSite/content/english/about.md, exampleSite/content/english/contact.md, exampleSite/content/english/faq.md, exampleSite/content/english/pricing.md, exampleSite/content/english/project/_index.md, exampleSite/content/english/service.md, exampleSite/content/french/about.md, exampleSite/content/french/contact.md, exampleSite/content/french/faq.md, exampleSite/content/french/pricing.md, exampleSite/content/french/project/_index.md, exampleSite/content/french/service.md, exampleSite/content/german/about.md, exampleSite/content/german/contact.md, exampleSite/content/german/faq.md, exampleSite/content/german/pricing.md, exampleSite/content/german/project/_index.md, exampleSite/content/german/service.md, exampleSite/content/italian/about.md, exampleSite/content/italian/contact.md, exampleSite/content/italian/faq.md, exampleSite/content/italian/pricing.md, exampleSite/content/italian/project/_index.md, exampleSite/content/italian/service.md
This simplifies menu adjustments since the content and its menu entries are now all found in the same place. E.g. you can now simply set `draft = true` in a specific content file and all its menu entries will automatically be disabled (i.e. have draft status), too, without the extra need to modify `config.toml` anymore.
Cf. #149
=> Move footer menu definitions to content files

netlify.toml
This rule has somehow been lost before.
=> Add Netlify redirect rule for German subpages

exampleSite/config.toml
cf. https://gohugo.io/getting-started/configuration/#timezone
Depends on #185 which increases the minimally required Hugo version to v0.87.0.
=> Set default `timeZone`

layouts/partials/head.html
The Matomo documentation states the tracking code should use matomo named files:
https://developer.matomo.org/guides/tracking-javascript-guide
The `piwik.*` files are still available in latest versions of Matomo but I suspect they could remove them at any time since they are incrementally getting rid ot this old name.
=> Use matomo.{js,php} in matomo tracking code

layouts/partials/head.html
There is one `manifest.webmanifest` generated per language, then link to the manifest of the current language.
=> Link to webmanifest in lang sub-directory

exampleSite/config/_default/params.toml, layouts/partials/head.html
counter.dev recently switched to using an external script, cf. https://counter.dev/blog/external-tracking-script.html
Additionally made sure that the site successfully builds in case the `params.plausible` config is absent.
=> Update counter.dev analytics
